import {
  Column,
  CreateDateColumn,
  Entity,
  OneToMany,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { QuizAnswer } from './quiz-answer.entity';

export enum QuizStatus {
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
}

@Entity('quiz_sessions')
export class QuizSession {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', default: QuizStatus.IN_PROGRESS })
  status: QuizStatus;

  @Column({ type: 'int', default: 0 })
  totalQuestions: number;

  @Column({ type: 'int', default: 0 })
  answeredCount: number;

  @Column({ type: 'int', default: 0 })
  correctCount: number;

  @Column({ type: 'text', nullable: true })
  questionIds: string; // JSON array of question ids in this session

  @Column({ type: 'boolean', default: false })
  isScheduled: boolean; // true = auto-generated by scheduler

  @CreateDateColumn()
  createdAt: Date;

  @Column({ type: 'datetime', nullable: true })
  completedAt: Date;

  @OneToMany(() => QuizAnswer, (a) => a.session)
  answers: QuizAnswer[];
}
