-- ============================================================
-- Art Exam System – Supabase schema for the NestJS quiz app
-- Apply in Supabase SQL editor before running the root app
-- ============================================================

create extension if not exists "pgcrypto";

create or replace function public.set_exam_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.exam_questions (
  id          bigint generated by default as identity primary key,
  content     text not null unique,
  image_url   text,
  options     jsonb not null,
  answer      text not null,
  explanation text not null,
  type        text not null default 'single_choice',
  period      text not null default 'modern',
  source      text,
  difficulty  int not null default 1,
  tags        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.exam_quiz_sessions (
  id              bigint generated by default as identity primary key,
  status          text not null default 'in_progress',
  total_questions int not null default 0,
  answered_count  int not null default 0,
  correct_count   int not null default 0,
  question_ids    jsonb not null default '[]'::jsonb,
  is_scheduled    boolean not null default false,
  created_at      timestamptz not null default now(),
  completed_at    timestamptz
);

create table if not exists public.exam_quiz_answers (
  id          bigint generated by default as identity primary key,
  session_id  bigint not null references public.exam_quiz_sessions(id) on delete cascade,
  question_id bigint not null references public.exam_questions(id) on delete cascade,
  user_answer text,
  is_correct  boolean not null default false,
  answered_at timestamptz not null default now(),
  unique (session_id, question_id)
);

create index if not exists idx_exam_questions_period on public.exam_questions(period);
create index if not exists idx_exam_questions_difficulty on public.exam_questions(difficulty);
create index if not exists idx_exam_quiz_sessions_created_at on public.exam_quiz_sessions(created_at desc);
create index if not exists idx_exam_quiz_answers_session_id on public.exam_quiz_answers(session_id);

drop trigger if exists trg_exam_questions_updated_at on public.exam_questions;
create trigger trg_exam_questions_updated_at
before update on public.exam_questions
for each row execute function public.set_exam_updated_at();

alter table public.exam_questions enable row level security;
alter table public.exam_quiz_sessions enable row level security;
alter table public.exam_quiz_answers enable row level security;

drop policy if exists "exam_questions_service_role" on public.exam_questions;
create policy "exam_questions_service_role" on public.exam_questions
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "exam_quiz_sessions_service_role" on public.exam_quiz_sessions;
create policy "exam_quiz_sessions_service_role" on public.exam_quiz_sessions
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "exam_quiz_answers_service_role" on public.exam_quiz_answers;
create policy "exam_quiz_answers_service_role" on public.exam_quiz_answers
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');